import type { Color, PDFFont, PDFPage } from 'pdf-lib';

import type {
	CrosswordPdfMode,
	CrosswordPdfResult
} from '$lib/features/crossword/crossword-export.types';

import { MAX_CROSSWORD_TITLE_LENGTH } from '$lib/features/crossword/crossword.constants';

import type { CrosswordEntry, CrosswordLayout } from '$lib/features/crossword/crossword.types';

import { normalizeAnswer } from '$lib/features/crossword/crossword.utils';

/**
 * Halaman "Daftar Soal" selalu portrait A4.
 *
 * Ukuran kertasnya dibuat fix dan terpisah dari halaman grid supaya
 * daftar soal tetap nyaman dibaca/di-print sebagai teks, tidak ikut
 * berubah mengikuti seberapa besar grid crossword-nya.
 */
const A4_PORTRAIT: [number, number] = [595.28, 841.89];

/**
 * Halaman grid (TTS kosong & kunci jawaban) selalu landscape A3.
 *
 * Grid crossword bisa sangat lebar/tinggi (puluhan kolom/baris), jadi
 * kertas dibuat fix ke A3 supaya cell tidak jadi kekecilan dibandingkan
 * dipaksakan ke A4.
 */
const A3_LANDSCAPE: [number, number] = [1190.55, 841.89];

const PAGE_MARGIN = 44;

const MAX_CELL_SIZE = 24;

/**
 * Ruang vertikal yang disisakan di bagian bawah grid page untuk footer.
 */
const FOOTER_RESERVED_HEIGHT = 40;

type PdfColors = {
	black: Color;
	muted: Color;
	border: Color;
};

function toPdfSafeText(value: string): string {
	return value
		.normalize('NFKD')
		.replace(/[\u0300-\u036f]/g, '')
		.replace(/[–—]/g, '-')
		.replace(/[""]/g, '"')
		.replace(/['']/g, "'")
		.replace(/[^\x20-\x7E\xA0-\xFF]/g, '?');
}

function wrapPdfText(text: string, font: PDFFont, fontSize: number, maxWidth: number): string[] {
	const words = toPdfSafeText(text).split(/\s+/).filter(Boolean);

	const lines: string[] = [];

	let currentLine = '';

	for (const word of words) {
		const candidate = currentLine ? `${currentLine} ${word}` : word;

		if (font.widthOfTextAtSize(candidate, fontSize) <= maxWidth) {
			currentLine = candidate;

			continue;
		}

		if (currentLine) {
			lines.push(currentLine);
		}

		currentLine = word;
	}

	if (currentLine) {
		lines.push(currentLine);
	}

	return lines.length > 0 ? lines : [''];
}

function drawPageFooter(page: PDFPage, font: PDFFont, colors: PdfColors): void {
	page.drawText('Generated by TTS Generator - wiraananda.vercel.app', {
		x: PAGE_MARGIN,

		y: 20,

		size: 8,

		font,

		color: colors.muted
	});
}

/**
 * Menggambar judul TTS (jika diisi) sebagai baris kecil di atas heading
 * section (TTS Kosong / Daftar Soal / Kunci Jawaban).
 *
 * Mengembalikan posisi y setelah baris judul terakhir, atau y awal apa
 * adanya jika judul kosong, supaya heading di bawahnya tetap konsisten
 * posisinya baik judul diisi maupun tidak.
 */
function drawCrosswordTitle(
	page: PDFPage,
	crosswordTitle: string,
	startY: number,
	fontSize: number,
	boldFont: PDFFont,
	colors: PdfColors
): number {
	const trimmedTitle = crosswordTitle.trim();

	if (!trimmedTitle) {
		return startY;
	}

	const { width } = page.getSize();

	const maxWidth = width - PAGE_MARGIN * 2;

	const titleLines = wrapPdfText(trimmedTitle, boldFont, fontSize, maxWidth);

	let y = startY;

	for (const line of titleLines) {
		page.drawText(line, {
			x: PAGE_MARGIN,

			y,

			size: fontSize,

			font: boldFont,

			color: colors.muted
		});

		y -= fontSize + 5;
	}

	return y - 4;
}

function drawCrosswordGrid(
	page: PDFPage,
	layout: CrosswordLayout,
	font: PDFFont,
	boldFont: PDFFont,
	colors: PdfColors,
	showAnswers: boolean,
	contentTop: number
): void {
	const { width: pageWidth } = page.getSize();

	const availableWidth = pageWidth - PAGE_MARGIN * 2;

	const availableHeight = contentTop - FOOTER_RESERVED_HEIGHT;

	const cellSize = Math.min(
		MAX_CELL_SIZE,

		availableWidth / layout.width,

		availableHeight / layout.height
	);

	const gridWidth = layout.width * cellSize;

	const gridHeight = layout.height * cellSize;

	const startX = (pageWidth - gridWidth) / 2;

	const startY = FOOTER_RESERVED_HEIGHT + (availableHeight - gridHeight) / 2;

	for (const cell of layout.cells) {
		const x = startX + cell.x * cellSize;

		const y = startY + gridHeight - (cell.y + 1) * cellSize;

		page.drawRectangle({
			x,
			y,

			width: cellSize,

			height: cellSize,

			borderWidth: 0.7,

			borderColor: colors.black
		});

		if (cell.numbers && cell.numbers.length > 0) {
			page.drawText(cell.numbers.join('/'), {
				x: x + 1.5,

				y: y + cellSize - 5,

				size: Math.max(4, cellSize * 0.18),

				font,

				color: colors.black
			});
		}

		if (!showAnswers) {
			continue;
		}

		const fontSize = Math.min(12, cellSize * 0.5);

		const letterWidth = boldFont.widthOfTextAtSize(cell.letter, fontSize);

		page.drawText(cell.letter, {
			x: x + (cellSize - letterWidth) / 2,

			y: y + cellSize * 0.29,

			size: fontSize,

			font: boldFont,

			color: colors.black
		});
	}
}

function drawGridSection(
	pdfDocument: import('pdf-lib').PDFDocument,
	layout: CrosswordLayout,
	font: PDFFont,
	boldFont: PDFFont,
	colors: PdfColors,
	heading: string,
	description: string,
	showAnswers: boolean,
	crosswordTitle: string
): void {
	const page = pdfDocument.addPage(A3_LANDSCAPE);

	const { height } = page.getSize();

	let y = height - PAGE_MARGIN;

	y = drawCrosswordTitle(page, crosswordTitle, y, 13, boldFont, colors);

	page.drawText(heading, {
		x: PAGE_MARGIN,

		y,

		size: 18,

		font: boldFont,

		color: colors.black
	});

	y -= 20;

	page.drawText(description, {
		x: PAGE_MARGIN,

		y,

		size: 9,

		font,

		color: colors.muted
	});

	y -= 16;

	drawCrosswordGrid(page, layout, font, boldFont, colors, showAnswers, y);

	drawPageFooter(page, font, colors);
}

function drawQuestionPages(
	pdfDocument: import('pdf-lib').PDFDocument,
	entries: CrosswordEntry[],
	layout: CrosswordLayout,
	font: PDFFont,
	boldFont: PDFFont,
	colors: PdfColors,
	crosswordTitle: string
): void {
	const directionByEntryId = new Map(
		layout.placements.map((placement) => [placement.entryId, placement.direction])
	);

	const activeEntries = entries
		.map((entry, index) => ({
			entry,
			number: index + 1
		}))
		.filter(({ entry }) => normalizeAnswer(entry.answer) !== '');

	let page = pdfDocument.addPage(A4_PORTRAIT);

	let y = page.getHeight() - PAGE_MARGIN;

	function drawHeader(continued = false): void {
		y = drawCrosswordTitle(page, crosswordTitle, y, 11, boldFont, colors);

		page.drawText(continued ? 'Daftar Soal - Lanjutan' : 'Daftar Soal', {
			x: PAGE_MARGIN,

			y,

			size: 18,

			font: boldFont,

			color: colors.black
		});

		y -= 28;
	}

	drawHeader();

	for (const { entry, number } of activeEntries) {
		const direction = directionByEntryId.get(entry.id);

		const directionLabel = direction === 'across' ? 'Mendatar' : 'Menurun';

		const text = `${number}. ${entry.clue.trim()} (${directionLabel})`;

		const lines = wrapPdfText(text, font, 10, page.getWidth() - PAGE_MARGIN * 2);

		const requiredHeight = lines.length * 14 + 8;

		if (y - requiredHeight < 40) {
			drawPageFooter(page, font, colors);

			page = pdfDocument.addPage(A4_PORTRAIT);

			y = page.getHeight() - PAGE_MARGIN;

			drawHeader(true);
		}

		for (const line of lines) {
			page.drawText(line, {
				x: PAGE_MARGIN,

				y,

				size: 10,

				font,

				color: colors.black
			});

			y -= 14;
		}

		y -= 5;
	}

	drawPageFooter(page, font, colors);
}

/**
 * Membersihkan judul supaya aman dipakai sebagai nama file di berbagai OS.
 */
function sanitizePdfFileNameSegment(value: string): string {
	return value
		.replace(/[\\/:*?"<>|]+/g, '-')
		.replace(/\s+/g, ' ')
		.trim()
		.slice(0, MAX_CROSSWORD_TITLE_LENGTH);
}

/**
 * Suffix nama file per mode, supaya 3 mode download tidak saling
 * menimpa file satu sama lain kalau judulnya sama.
 *
 * Mode 'complete' sengaja tidak diberi suffix supaya nama file tetap
 * persis sama dengan judul TTS, seperti behavior sebelum ada mode lain.
 */
const PDF_MODE_FILE_NAME_SUFFIX: Record<CrosswordPdfMode, string> = {
	complete: '',
	'puzzle-and-questions': ' - TTS & Soal',
	'puzzle-only': ' - TTS Kosong'
};

const PDF_MODE_TIMESTAMP_SUFFIX: Record<CrosswordPdfMode, string> = {
	complete: '',
	'puzzle-and-questions': '-tts-soal',
	'puzzle-only': '-tts-kosong'
};

function createTimestampPdfFileName(mode: CrosswordPdfMode): string {
	const date = new Date();

	const pad = (value: number): string => String(value).padStart(2, '0');

	const base = [
		'tts',
		`${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}`,
		`${pad(date.getHours())}${pad(date.getMinutes())}`
	].join('-');

	return `${base}${PDF_MODE_TIMESTAMP_SUFFIX[mode]}.pdf`;
}

/**
 * Judul TTS (jika diisi) dipakai sebagai nama file.
 *
 * Fallback ke nama berbasis tanggal/jam jika judul kosong, atau
 * menjadi kosong setelah disanitasi (misal isinya simbol semua).
 */
function createPdfFileName(crosswordTitle: string, mode: CrosswordPdfMode): string {
	const safeTitle = sanitizePdfFileNameSegment(crosswordTitle);

	if (!safeTitle) {
		return createTimestampPdfFileName(mode);
	}

	return `${safeTitle}${PDF_MODE_FILE_NAME_SUFFIX[mode]}.pdf`;
}

/**
 * Membuat satu PDF sesuai mode:
 *
 * - 'complete': TTS kosong (A3 landscape) + Daftar soal (A4 portrait) +
 *   Kunci jawaban (A3 landscape).
 * - 'puzzle-and-questions': TTS kosong (A3 landscape) + Daftar soal
 *   (A4 portrait) saja, tanpa Kunci jawaban.
 * - 'puzzle-only': TTS kosong (A3 landscape) saja, tanpa Daftar soal
 *   dan tanpa Kunci jawaban.
 *
 * crosswordTitle bersifat opsional. Jika diisi, judul akan muncul
 * di setiap halaman dan dipakai sebagai PDF document title.
 */
export async function generateCrosswordPdfBytes(
	entries: CrosswordEntry[],
	layout: CrosswordLayout,
	crosswordTitle = '',
	mode: CrosswordPdfMode = 'complete'
): Promise<Uint8Array> {
	const { PDFDocument, StandardFonts, rgb } = await import('pdf-lib');

	const pdfDocument = await PDFDocument.create();

	pdfDocument.setTitle(crosswordTitle.trim() || 'TTS Generator');

	pdfDocument.setAuthor('Wiraa');

	const font = await pdfDocument.embedFont(StandardFonts.Helvetica);

	const boldFont = await pdfDocument.embedFont(StandardFonts.HelveticaBold);

	const colors: PdfColors = {
		black: rgb(0, 0, 0),

		muted: rgb(0.35, 0.35, 0.35),

		border: rgb(0.5, 0.5, 0.5)
	};

	/**
	 * Deskripsi halaman TTS Kosong menyesuaikan mode: kalau tidak ada
	 * halaman Daftar Soal (mode 'puzzle-only'), jangan menyebut
	 * "halaman berikutnya" karena halaman itu tidak ada.
	 */
	const blankGridDescription =
		mode === 'puzzle-only'
			? 'Kotak kosong untuk diisi jawaban teka-teki silang.'
			: 'Isi kotak berdasarkan daftar soal pada halaman berikutnya.';

	drawGridSection(
		pdfDocument,
		layout,
		font,
		boldFont,
		colors,
		'TTS Kosong',
		blankGridDescription,
		false,
		crosswordTitle
	);

	if (mode !== 'puzzle-only') {
		drawQuestionPages(pdfDocument, entries, layout, font, boldFont, colors, crosswordTitle);
	}

	if (mode === 'complete') {
		drawGridSection(
			pdfDocument,
			layout,
			font,
			boldFont,
			colors,
			'Kunci Jawaban',
			'Crossword lengkap dengan jawaban.',
			true,
			crosswordTitle
		);
	}

	return pdfDocument.save();
}

/**
 * Generate kemudian memulai browser download.
 *
 * Nama file mengikuti judul TTS (jika diisi) + suffix sesuai mode,
 * fallback ke nama berbasis tanggal/jam seperti sebelumnya jika judul
 * kosong.
 */
export async function downloadCrosswordPdf(
	entries: CrosswordEntry[],
	layout: CrosswordLayout,
	crosswordTitle = '',
	mode: CrosswordPdfMode = 'complete'
): Promise<CrosswordPdfResult> {
	const bytes = await generateCrosswordPdfBytes(entries, layout, crosswordTitle, mode);

	const fileName = createPdfFileName(crosswordTitle, mode);

	const blob = new Blob([bytes], {
		type: 'application/pdf'
	});

	const url = URL.createObjectURL(blob);

	const anchor = document.createElement('a');

	anchor.href = url;

	anchor.download = fileName;

	document.body.appendChild(anchor);

	anchor.click();

	anchor.remove();

	URL.revokeObjectURL(url);

	return {
		fileName,

		downloadedAt: new Date().toISOString()
	};
}
