import type { Color, PDFFont, PDFPage } from 'pdf-lib';

import type {
	CrosswordPdfMode,
	CrosswordPdfResult
} from '$lib/features/crossword/crossword-export.types';

import { MAX_CROSSWORD_TITLE_LENGTH } from '$lib/features/crossword/crossword.constants';

import type { CrosswordEntry, CrosswordLayout } from '$lib/features/crossword/crossword.types';

import { normalizeAnswer } from '$lib/features/crossword/crossword.utils';

/**
 * Halaman "Daftar Soal" selalu portrait A4.
 *
 * Ukuran kertasnya dibuat fix dan terpisah dari halaman grid supaya
 * daftar soal tetap nyaman dibaca/di-print sebagai teks, tidak ikut
 * berubah mengikuti seberapa besar grid crossword-nya.
 */
const A4_PORTRAIT: [number, number] = [595.28, 841.89];

/**
 * Halaman grid (TTS kosong & kunci jawaban) selalu landscape A3.
 *
 * Grid crossword bisa sangat lebar/tinggi (puluhan kolom/baris), jadi
 * kertas dibuat fix ke A3 supaya cell tidak jadi kekecilan dibandingkan
 * dipaksakan ke A4.
 */
const A3_LANDSCAPE: [number, number] = [1190.55, 841.89];

const PAGE_MARGIN = 44;

/**
 * Ukuran cell maksimum. Dinaikkan supaya kotak lebih besar dan lebih
 * nyaman diisi tangan — baru mengecil otomatis kalau grid-nya memang
 * terlalu lebar/tinggi untuk muat di kertas A3.
 */
const MAX_CELL_SIZE = 32;

/**
 * Setiap cell dibagi 2 zona vertikal, dengan gap kosong di antaranya:
 * zona nomor (strip kecil di atas) dan zona huruf (sisa ruang di
 * bawah). Font size nomor & huruf masing-masing hanya mengisi
 * sebagian dari tinggi zona-nya sendiri (bukan penuh) supaya selalu
 * ada jarak aman — bukan cuma nggak numpuk secara matematis, tapi
 * benar-benar ada spasi kosong di antara keduanya secara visual.
 */
const NUMBER_ZONE_HEIGHT_RATIO = 0.32;

const NUMBER_ZONE_FILL_RATIO = 0.72;

const ZONE_GAP_RATIO = 0.03;

const MAX_NUMBER_FONT_SIZE = 8;

/**
 * Floor ini cuma jaring pengaman supaya font size nggak pernah 0/minus
 * saat proses "shrink to fit" untuk nomor gabungan (mis. "45/78") —
 * bukan target keterbacaan minimum, karena mencegah tabrakan selalu
 * lebih penting daripada memaksakan ukuran tertentu.
 */
const MIN_NUMBER_FONT_SIZE = 2;

const MAX_LETTER_FONT_SIZE = 16;

const LETTER_ZONE_FONT_RATIO = 0.72;

/**
 * Ruang vertikal yang disisakan di bagian bawah grid page untuk footer.
 */
const FOOTER_RESERVED_HEIGHT = 40;

type PdfColors = {
	black: Color;
	muted: Color;
	border: Color;
};

function toPdfSafeText(value: string): string {
	return value
		.normalize('NFKD')
		.replace(/[\u0300-\u036f]/g, '')
		.replace(/[–—]/g, '-')
		.replace(/[""]/g, '"')
		.replace(/['']/g, "'")
		.replace(/[^\x20-\x7E\xA0-\xFF]/g, '?');
}

function wrapPdfText(text: string, font: PDFFont, fontSize: number, maxWidth: number): string[] {
	const words = toPdfSafeText(text).split(/\s+/).filter(Boolean);

	const lines: string[] = [];

	let currentLine = '';

	for (const word of words) {
		const candidate = currentLine ? `${currentLine} ${word}` : word;

		if (font.widthOfTextAtSize(candidate, fontSize) <= maxWidth) {
			currentLine = candidate;

			continue;
		}

		if (currentLine) {
			lines.push(currentLine);
		}

		currentLine = word;
	}

	if (currentLine) {
		lines.push(currentLine);
	}

	return lines.length > 0 ? lines : [''];
}

function drawPageFooter(page: PDFPage, font: PDFFont, colors: PdfColors): void {
	page.drawText('Generated by TTS Generator - wiraananda.vercel.app', {
		x: PAGE_MARGIN,

		y: 20,

		size: 8,

		font,

		color: colors.muted
	});
}

/**
 * Menggambar judul TTS (jika diisi) sebagai baris kecil di atas heading
 * section (TTS Kosong / Daftar Soal / Kunci Jawaban).
 *
 * Mengembalikan posisi y setelah baris judul terakhir, atau y awal apa
 * adanya jika judul kosong, supaya heading di bawahnya tetap konsisten
 * posisinya baik judul diisi maupun tidak.
 */
function drawCrosswordTitle(
	page: PDFPage,
	crosswordTitle: string,
	startY: number,
	fontSize: number,
	boldFont: PDFFont,
	colors: PdfColors
): number {
	const trimmedTitle = crosswordTitle.trim();

	if (!trimmedTitle) {
		return startY;
	}

	const { width } = page.getSize();

	const maxWidth = width - PAGE_MARGIN * 2;

	const titleLines = wrapPdfText(trimmedTitle, boldFont, fontSize, maxWidth);

	let y = startY;

	for (const line of titleLines) {
		page.drawText(line, {
			x: PAGE_MARGIN,

			y,

			size: fontSize,

			font: boldFont,

			color: colors.muted
		});

		y -= fontSize + 5;
	}

	return y - 4;
}

/**
 * 'none': semua cell kosong (TTS Kosong).
 * 'first-letters': hanya cell bernomor (starting cell across/down) yang
 *   diisi huruf, sisanya kosong (TTS Awalan).
 * 'all': semua cell diisi huruf (Kunci Jawaban).
 */
type CrosswordGridLetterReveal = 'none' | 'first-letters' | 'all';

function drawCrosswordGrid(
	page: PDFPage,
	layout: CrosswordLayout,
	boldFont: PDFFont,
	colors: PdfColors,
	letterReveal: CrosswordGridLetterReveal,
	contentTop: number
): void {
	const { width: pageWidth } = page.getSize();

	const availableWidth = pageWidth - PAGE_MARGIN * 2;

	const availableHeight = contentTop - FOOTER_RESERVED_HEIGHT;

	const cellSize = Math.min(
		MAX_CELL_SIZE,

		availableWidth / layout.width,

		availableHeight / layout.height
	);

	const gridWidth = layout.width * cellSize;

	const gridHeight = layout.height * cellSize;

	const startX = (pageWidth - gridWidth) / 2;

	const startY = FOOTER_RESERVED_HEIGHT + (availableHeight - gridHeight) / 2;

	const numberZoneHeight = cellSize * NUMBER_ZONE_HEIGHT_RATIO;

	const zoneGap = Math.max(1, cellSize * ZONE_GAP_RATIO);

	const letterZoneHeight = cellSize - numberZoneHeight - zoneGap;

	const baseNumberFontSize = Math.min(
		MAX_NUMBER_FONT_SIZE,
		numberZoneHeight * NUMBER_ZONE_FILL_RATIO
	);

	const letterFontSize = Math.min(MAX_LETTER_FONT_SIZE, letterZoneHeight * LETTER_ZONE_FONT_RATIO);

	for (const cell of layout.cells) {
		const x = startX + cell.x * cellSize;

		const y = startY + gridHeight - (cell.y + 1) * cellSize;

		page.drawRectangle({
			x,
			y,

			width: cellSize,

			height: cellSize,

			borderWidth: 0.7,

			borderColor: colors.black
		});

		const isStartingCell = Boolean(cell.numbers && cell.numbers.length > 0);

		if (isStartingCell) {
			const numberText = cell.numbers!.join('/');

			/**
			 * Cell dengan lebih dari satu nomor (mis. "45/78") bisa lebih
			 * lebar dari cell-nya sendiri di font size normal — kecilkan
			 * bertahap sampai muat, supaya tidak meluber ke cell sebelah
			 * atau ke area huruf.
			 */
			let numberFontSize = baseNumberFontSize;

			const maxNumberWidth = cellSize - 4;

			while (
				numberFontSize > MIN_NUMBER_FONT_SIZE &&
				boldFont.widthOfTextAtSize(numberText, numberFontSize) > maxNumberWidth
			) {
				numberFontSize -= 0.5;
			}

			page.drawText(numberText, {
				x: x + 2,

				y: y + cellSize - numberFontSize - 1,

				size: numberFontSize,

				font: boldFont,

				color: colors.black
			});
		}

		/**
		 * 'first-letters' hanya mengisi starting cell (cell yang punya
		 * nomor) — itu satu-satunya cell yang huruf pertamanya jadi
		 * petunjuk. Cell lain tetap kosong seperti TTS Kosong biasa.
		 */
		const shouldRevealLetter =
			letterReveal === 'all' || (letterReveal === 'first-letters' && isStartingCell);

		if (!shouldRevealLetter) {
			continue;
		}

		const letterWidth = boldFont.widthOfTextAtSize(cell.letter, letterFontSize);

		page.drawText(cell.letter, {
			x: x + (cellSize - letterWidth) / 2,

			y: y + (letterZoneHeight - letterFontSize * 0.72) / 2,

			size: letterFontSize,

			font: boldFont,

			color: colors.black
		});
	}
}

function drawGridSection(
	pdfDocument: import('pdf-lib').PDFDocument,
	layout: CrosswordLayout,
	font: PDFFont,
	boldFont: PDFFont,
	colors: PdfColors,
	heading: string,
	description: string,
	letterReveal: CrosswordGridLetterReveal,
	crosswordTitle: string
): void {
	const page = pdfDocument.addPage(A3_LANDSCAPE);

	const { height } = page.getSize();

	let y = height - PAGE_MARGIN;

	y = drawCrosswordTitle(page, crosswordTitle, y, 13, boldFont, colors);

	page.drawText(heading, {
		x: PAGE_MARGIN,

		y,

		size: 18,

		font: boldFont,

		color: colors.black
	});

	y -= 20;

	page.drawText(description, {
		x: PAGE_MARGIN,

		y,

		size: 9,

		font,

		color: colors.muted
	});

	y -= 16;

	drawCrosswordGrid(page, layout, boldFont, colors, letterReveal, y);

	drawPageFooter(page, font, colors);
}

function drawQuestionPages(
	pdfDocument: import('pdf-lib').PDFDocument,
	entries: CrosswordEntry[],
	layout: CrosswordLayout,
	font: PDFFont,
	boldFont: PDFFont,
	colors: PdfColors,
	crosswordTitle: string
): void {
	const directionByEntryId = new Map(
		layout.placements.map((placement) => [placement.entryId, placement.direction])
	);

	const activeEntries = entries
		.map((entry, index) => ({
			entry,
			number: index + 1
		}))
		.filter(({ entry }) => normalizeAnswer(entry.answer) !== '');

	let page = pdfDocument.addPage(A4_PORTRAIT);

	let y = page.getHeight() - PAGE_MARGIN;

	function drawHeader(continued = false): void {
		y = drawCrosswordTitle(page, crosswordTitle, y, 11, boldFont, colors);

		page.drawText(continued ? 'Daftar Soal - Lanjutan' : 'Daftar Soal', {
			x: PAGE_MARGIN,

			y,

			size: 18,

			font: boldFont,

			color: colors.black
		});

		y -= 28;
	}

	drawHeader();

	for (const { entry, number } of activeEntries) {
		const direction = directionByEntryId.get(entry.id);

		const directionLabel = direction === 'across' ? 'Mendatar' : 'Menurun';

		const text = `${number}. ${entry.clue.trim()} (${directionLabel})`;

		const lines = wrapPdfText(text, font, 10, page.getWidth() - PAGE_MARGIN * 2);

		const requiredHeight = lines.length * 14 + 8;

		if (y - requiredHeight < 40) {
			drawPageFooter(page, font, colors);

			page = pdfDocument.addPage(A4_PORTRAIT);

			y = page.getHeight() - PAGE_MARGIN;

			drawHeader(true);
		}

		for (const line of lines) {
			page.drawText(line, {
				x: PAGE_MARGIN,

				y,

				size: 10,

				font,

				color: colors.black
			});

			y -= 14;
		}

		y -= 5;
	}

	drawPageFooter(page, font, colors);
}

/**
 * Membersihkan judul supaya aman dipakai sebagai nama file di berbagai OS.
 */
function sanitizePdfFileNameSegment(value: string): string {
	return value
		.replace(/[\\/:*?"<>|]+/g, '-')
		.replace(/\s+/g, ' ')
		.trim()
		.slice(0, MAX_CROSSWORD_TITLE_LENGTH);
}

/**
 * Suffix nama file per mode, supaya semua mode download tidak saling
 * menimpa file satu sama lain kalau judulnya sama.
 *
 * Mode 'complete' sengaja tidak diberi suffix supaya nama file tetap
 * persis sama dengan judul TTS, seperti behavior sebelum ada mode lain.
 */
const PDF_MODE_FILE_NAME_SUFFIX: Record<CrosswordPdfMode, string> = {
	complete: '',
	'puzzle-and-questions': ' - TTS & Soal',
	'puzzle-only': ' - TTS Kosong',
	'puzzle-first-letters': ' - TTS Awalan',
	'questions-only': ' - Soal',
	'answer-key-only': ' - Kunci Jawaban'
};

const PDF_MODE_TIMESTAMP_SUFFIX: Record<CrosswordPdfMode, string> = {
	complete: '',
	'puzzle-and-questions': '-tts-soal',
	'puzzle-only': '-tts-kosong',
	'puzzle-first-letters': '-tts-awalan',
	'questions-only': '-soal',
	'answer-key-only': '-kunci-jawaban'
};

function createTimestampPdfFileName(mode: CrosswordPdfMode): string {
	const date = new Date();

	const pad = (value: number): string => String(value).padStart(2, '0');

	const base = [
		'tts',
		`${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}`,
		`${pad(date.getHours())}${pad(date.getMinutes())}`
	].join('-');

	return `${base}${PDF_MODE_TIMESTAMP_SUFFIX[mode]}.pdf`;
}

/**
 * Judul TTS (jika diisi) dipakai sebagai nama file.
 *
 * Fallback ke nama berbasis tanggal/jam jika judul kosong, atau
 * menjadi kosong setelah disanitasi (misal isinya simbol semua).
 */
function createPdfFileName(crosswordTitle: string, mode: CrosswordPdfMode): string {
	const safeTitle = sanitizePdfFileNameSegment(crosswordTitle);

	if (!safeTitle) {
		return createTimestampPdfFileName(mode);
	}

	return `${safeTitle}${PDF_MODE_FILE_NAME_SUFFIX[mode]}.pdf`;
}

/**
 * Membuat satu PDF sesuai mode:
 *
 * - 'complete': TTS kosong (A3 landscape) + Daftar soal (A4 portrait) +
 *   Kunci jawaban (A3 landscape).
 * - 'puzzle-and-questions': TTS kosong (A3 landscape) + Daftar soal
 *   (A4 portrait) saja, tanpa Kunci jawaban.
 * - 'puzzle-only': TTS kosong (A3 landscape) saja, tanpa Daftar soal
 *   dan tanpa Kunci jawaban.
 * - 'puzzle-first-letters': TTS Awalan (A3 landscape) saja — huruf pertama
 *   tiap nomor terisi sebagai petunjuk, tanpa Daftar soal dan tanpa
 *   Kunci jawaban.
 * - 'questions-only': Daftar soal (A4 portrait) saja, tanpa halaman grid
 *   sama sekali.
 * - 'answer-key-only': Kunci jawaban (A3 landscape) saja, tanpa Daftar
 *   soal.
 *
 * crosswordTitle bersifat opsional. Jika diisi, judul akan muncul
 * di setiap halaman dan dipakai sebagai PDF document title.
 */
export async function generateCrosswordPdfBytes(
	entries: CrosswordEntry[],
	layout: CrosswordLayout,
	crosswordTitle = '',
	mode: CrosswordPdfMode = 'complete'
): Promise<Uint8Array> {
	const { PDFDocument, StandardFonts, rgb } = await import('pdf-lib');

	const pdfDocument = await PDFDocument.create();

	pdfDocument.setTitle(crosswordTitle.trim() || 'TTS Generator');

	pdfDocument.setAuthor('Wiraa');

	const font = await pdfDocument.embedFont(StandardFonts.Helvetica);

	const boldFont = await pdfDocument.embedFont(StandardFonts.HelveticaBold);

	const colors: PdfColors = {
		black: rgb(0, 0, 0),

		muted: rgb(0.35, 0.35, 0.35),

		border: rgb(0.5, 0.5, 0.5)
	};

	const drawBlankGrid = (description: string): void => {
		drawGridSection(
			pdfDocument,
			layout,
			font,
			boldFont,
			colors,
			'TTS Kosong',
			description,
			'none',
			crosswordTitle
		);
	};

	const drawQuestions = (): void => {
		drawQuestionPages(pdfDocument, entries, layout, font, boldFont, colors, crosswordTitle);
	};

	const drawAnswerKey = (): void => {
		drawGridSection(
			pdfDocument,
			layout,
			font,
			boldFont,
			colors,
			'Kunci Jawaban',
			'Crossword lengkap dengan jawaban.',
			'all',
			crosswordTitle
		);
	};

	switch (mode) {
		case 'puzzle-first-letters': {
			drawGridSection(
				pdfDocument,
				layout,
				font,
				boldFont,
				colors,
				'TTS Awalan',
				'Huruf pertama setiap nomor sudah diisi sebagai petunjuk.',
				'first-letters',
				crosswordTitle
			);

			break;
		}

		case 'puzzle-only': {
			drawBlankGrid('Kotak kosong untuk diisi jawaban teka-teki silang.');

			break;
		}

		case 'questions-only': {
			drawQuestions();

			break;
		}

		case 'answer-key-only': {
			drawAnswerKey();

			break;
		}

		case 'puzzle-and-questions': {
			drawBlankGrid('Isi kotak berdasarkan daftar soal pada halaman berikutnya.');

			drawQuestions();

			break;
		}

		case 'complete': {
			drawBlankGrid('Isi kotak berdasarkan daftar soal pada halaman berikutnya.');

			drawQuestions();

			drawAnswerKey();

			break;
		}

		default: {
			/**
			 * Exhaustiveness guard: kalau ada CrosswordPdfMode baru yang
			 * belum ditangani di atas, TypeScript akan error di sini
			 * pada saat compile, bukan silently ke-skip saat runtime.
			 */
			const unhandledMode: never = mode;

			throw new Error(`Mode PDF tidak dikenali: ${unhandledMode}`);
		}
	}

	return pdfDocument.save();
}

/**
 * Generate kemudian memulai browser download.
 *
 * Nama file mengikuti judul TTS (jika diisi) + suffix sesuai mode,
 * fallback ke nama berbasis tanggal/jam seperti sebelumnya jika judul
 * kosong.
 */
export async function downloadCrosswordPdf(
	entries: CrosswordEntry[],
	layout: CrosswordLayout,
	crosswordTitle = '',
	mode: CrosswordPdfMode = 'complete'
): Promise<CrosswordPdfResult> {
	const bytes = await generateCrosswordPdfBytes(entries, layout, crosswordTitle, mode);

	const fileName = createPdfFileName(crosswordTitle, mode);

	const blob = new Blob([bytes], {
		type: 'application/pdf'
	});

	const url = URL.createObjectURL(blob);

	const anchor = document.createElement('a');

	anchor.href = url;

	anchor.download = fileName;

	document.body.appendChild(anchor);

	anchor.click();

	anchor.remove();

	URL.revokeObjectURL(url);

	return {
		fileName,

		downloadedAt: new Date().toISOString()
	};
}
