import type { Color, PDFFont, PDFPage } from 'pdf-lib';

import type { CrosswordPdfResult } from '$lib/features/crossword/crossword-export.types';

import type { CrosswordEntry, CrosswordLayout } from '$lib/features/crossword/crossword.types';

import { normalizeAnswer } from '$lib/features/crossword/crossword.utils';

const A4_PORTRAIT: [number, number] = [595.28, 841.89];

const A4_LANDSCAPE: [number, number] = [841.89, 595.28];

const PAGE_MARGIN = 44;

type PdfColors = {
	black: Color;
	muted: Color;
	border: Color;
};

function toPdfSafeText(value: string): string {
	return value
		.normalize('NFKD')
		.replace(/[\u0300-\u036f]/g, '')
		.replace(/[–—]/g, '-')
		.replace(/[“”]/g, '"')
		.replace(/[‘’]/g, "'")
		.replace(/[^\x20-\x7E\xA0-\xFF]/g, '?');
}

function wrapPdfText(text: string, font: PDFFont, fontSize: number, maxWidth: number): string[] {
	const words = toPdfSafeText(text).split(/\s+/).filter(Boolean);

	const lines: string[] = [];

	let currentLine = '';

	for (const word of words) {
		const candidate = currentLine ? `${currentLine} ${word}` : word;

		if (font.widthOfTextAtSize(candidate, fontSize) <= maxWidth) {
			currentLine = candidate;

			continue;
		}

		if (currentLine) {
			lines.push(currentLine);
		}

		currentLine = word;
	}

	if (currentLine) {
		lines.push(currentLine);
	}

	return lines.length > 0 ? lines : [''];
}

function drawPageFooter(page: PDFPage, font: PDFFont, colors: PdfColors): void {
	page.drawText('Generated by TTS Generator - wiraananda.vercel.app', {
		x: PAGE_MARGIN,

		y: 20,

		size: 8,

		font,

		color: colors.muted
	});
}

function getGridPageSize(layout: CrosswordLayout): [number, number] {
	const calculateCellSize = (size: [number, number]): number => {
		const [width, height] = size;

		return Math.min(
			24,

			(width - PAGE_MARGIN * 2) / layout.width,

			(height - 150) / layout.height
		);
	};

	return calculateCellSize(A4_LANDSCAPE) > calculateCellSize(A4_PORTRAIT)
		? A4_LANDSCAPE
		: A4_PORTRAIT;
}

function drawCrosswordGrid(
	page: PDFPage,
	layout: CrosswordLayout,
	font: PDFFont,
	boldFont: PDFFont,
	colors: PdfColors,
	showAnswers: boolean
): void {
	const { width: pageWidth, height: pageHeight } = page.getSize();

	const availableWidth = pageWidth - PAGE_MARGIN * 2;

	const availableHeight = pageHeight - 150;

	const cellSize = Math.min(
		24,

		availableWidth / layout.width,

		availableHeight / layout.height
	);

	const gridWidth = layout.width * cellSize;

	const gridHeight = layout.height * cellSize;

	const startX = (pageWidth - gridWidth) / 2;

	const startY = (pageHeight - gridHeight) / 2 - 8;

	for (const cell of layout.cells) {
		const x = startX + cell.x * cellSize;

		const y = startY + gridHeight - (cell.y + 1) * cellSize;

		page.drawRectangle({
			x,
			y,

			width: cellSize,

			height: cellSize,

			borderWidth: 0.7,

			borderColor: colors.black
		});

		if (cell.numbers && cell.numbers.length > 0) {
			page.drawText(cell.numbers.join('/'), {
				x: x + 1.5,

				y: y + cellSize - 5,

				size: Math.max(4, cellSize * 0.18),

				font,

				color: colors.black
			});
		}

		if (!showAnswers) {
			continue;
		}

		const fontSize = Math.min(12, cellSize * 0.5);

		const letterWidth = boldFont.widthOfTextAtSize(cell.letter, fontSize);

		page.drawText(cell.letter, {
			x: x + (cellSize - letterWidth) / 2,

			y: y + cellSize * 0.29,

			size: fontSize,

			font: boldFont,

			color: colors.black
		});
	}
}

function drawGridSection(
	pdfDocument: import('pdf-lib').PDFDocument,
	layout: CrosswordLayout,
	font: PDFFont,
	boldFont: PDFFont,
	colors: PdfColors,
	title: string,
	description: string,
	showAnswers: boolean
): void {
	const page = pdfDocument.addPage(getGridPageSize(layout));

	const { height } = page.getSize();

	page.drawText(title, {
		x: PAGE_MARGIN,

		y: height - PAGE_MARGIN,

		size: 18,

		font: boldFont,

		color: colors.black
	});

	page.drawText(description, {
		x: PAGE_MARGIN,

		y: height - PAGE_MARGIN - 20,

		size: 9,

		font,

		color: colors.muted
	});

	drawCrosswordGrid(page, layout, font, boldFont, colors, showAnswers);

	drawPageFooter(page, font, colors);
}

function drawQuestionPages(
	pdfDocument: import('pdf-lib').PDFDocument,
	entries: CrosswordEntry[],
	layout: CrosswordLayout,
	font: PDFFont,
	boldFont: PDFFont,
	colors: PdfColors
): void {
	const directionByEntryId = new Map(
		layout.placements.map((placement) => [placement.entryId, placement.direction])
	);

	const activeEntries = entries
		.map((entry, index) => ({
			entry,
			number: index + 1
		}))
		.filter(({ entry }) => normalizeAnswer(entry.answer) !== '');

	let page = pdfDocument.addPage(A4_PORTRAIT);

	let y = page.getHeight() - PAGE_MARGIN;

	function drawHeader(continued = false): void {
		page.drawText(continued ? 'Daftar Soal - Lanjutan' : 'Daftar Soal', {
			x: PAGE_MARGIN,

			y,

			size: 18,

			font: boldFont,

			color: colors.black
		});

		y -= 28;
	}

	drawHeader();

	for (const { entry, number } of activeEntries) {
		const direction = directionByEntryId.get(entry.id);

		const directionLabel = direction === 'across' ? 'Mendatar' : 'Menurun';

		const text = `${number}. ${entry.clue.trim()} (${directionLabel})`;

		const lines = wrapPdfText(text, font, 10, page.getWidth() - PAGE_MARGIN * 2);

		const requiredHeight = lines.length * 14 + 8;

		if (y - requiredHeight < 40) {
			drawPageFooter(page, font, colors);

			page = pdfDocument.addPage(A4_PORTRAIT);

			y = page.getHeight() - PAGE_MARGIN;

			drawHeader(true);
		}

		for (const line of lines) {
			page.drawText(line, {
				x: PAGE_MARGIN,

				y,

				size: 10,

				font,

				color: colors.black
			});

			y -= 14;
		}

		y -= 5;
	}

	drawPageFooter(page, font, colors);
}

function createPdfFileName(): string {
	const date = new Date();

	const pad = (value: number): string => String(value).padStart(2, '0');

	return (
		[
			'tts',
			`${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}`,
			`${pad(date.getHours())}${pad(date.getMinutes())}`
		].join('-') + '.pdf'
	);
}

/**
 * Membuat satu PDF berisi:
 *
 * 1. TTS kosong
 * 2. Daftar soal
 * 3. Kunci jawaban
 */
export async function generateCrosswordPdfBytes(
	entries: CrosswordEntry[],
	layout: CrosswordLayout
): Promise<Uint8Array> {
	const { PDFDocument, StandardFonts, rgb } = await import('pdf-lib');

	const pdfDocument = await PDFDocument.create();

	pdfDocument.setTitle('TTS Generator');

	pdfDocument.setAuthor('Wiraa');

	const font = await pdfDocument.embedFont(StandardFonts.Helvetica);

	const boldFont = await pdfDocument.embedFont(StandardFonts.HelveticaBold);

	const colors: PdfColors = {
		black: rgb(0, 0, 0),

		muted: rgb(0.35, 0.35, 0.35),

		border: rgb(0.5, 0.5, 0.5)
	};

	drawGridSection(
		pdfDocument,
		layout,
		font,
		boldFont,
		colors,
		'TTS Kosong',
		'Isi kotak berdasarkan daftar soal pada halaman berikutnya.',
		false
	);

	drawQuestionPages(pdfDocument, entries, layout, font, boldFont, colors);

	drawGridSection(
		pdfDocument,
		layout,
		font,
		boldFont,
		colors,
		'Kunci Jawaban',
		'Crossword lengkap dengan jawaban.',
		true
	);

	return pdfDocument.save();
}

/**
 * Generate kemudian memulai browser download.
 */
export async function downloadCrosswordPdf(
	entries: CrosswordEntry[],
	layout: CrosswordLayout
): Promise<CrosswordPdfResult> {
	const bytes = await generateCrosswordPdfBytes(entries, layout);

	const fileName = createPdfFileName();

	const blob = new Blob([bytes], {
		type: 'application/pdf'
	});

	const url = URL.createObjectURL(blob);

	const anchor = document.createElement('a');

	anchor.href = url;

	anchor.download = fileName;

	document.body.appendChild(anchor);

	anchor.click();

	anchor.remove();

	URL.revokeObjectURL(url);

	return {
		fileName,

		downloadedAt: new Date().toISOString()
	};
}
