export const INITIAL_CROSSWORD_ENTRY_COUNT = 10;

export const MAX_CROSSWORD_ENTRY_COUNT = 150;

export const MAX_CROSSWORD_TITLE_LENGTH = 120;

export const CROSSWORD_AUTOSAVE_DELAY_MS = 650;

export const MAX_CROSSWORD_HISTORY_COUNT = 20;

export const CROSSWORD_GENERATION_DELAY_MS = 300;

export const CROSSWORD_LIVE_ATTEMPTS = 1;

export const CROSSWORD_IMPORT_MAX_FILE_SIZE_BYTES = 5 * 1024 * 1024;

export const CROSSWORD_IMPORT_MAX_SOURCE_ROWS = 2000;

export const CROSSWORD_IMPORT_PREVIEW_ROW_COUNT = 8;

export const CROSSWORD_IMPORT_MAX_VISIBLE_ISSUES = 50;
